[2024-04-30T17:08:43.132+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-04-30T17:08:40.688376+00:00 [queued]>
[2024-04-30T17:08:43.140+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-04-30T17:08:40.688376+00:00 [queued]>
[2024-04-30T17:08:43.141+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-04-30T17:08:43.141+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-04-30T17:08:43.142+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-04-30T17:08:43.150+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-04-30 17:08:40.688376+00:00
[2024-04-30T17:08:43.157+0000] {standard_task_runner.py:55} INFO - Started process 1310 to run task
[2024-04-30T17:08:43.161+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2024-04-30T17:08:40.688376+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpwv39pn25']
[2024-04-30T17:08:43.164+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask is_api_available
[2024-04-30T17:08:43.220+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2024-04-30T17:08:40.688376+00:00 [running]> on host ec0cac6d8211
[2024-04-30T17:08:43.266+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-04-30T17:08:40.688376+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-30T17:08:40.688376+00:00
[2024-04-30T17:08:43.267+0000] {http.py:120} INFO - Poking: api/
[2024-04-30T17:08:43.277+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-04-30T17:08:43.284+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-04-30T17:08:43.677+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2024-04-30T17:08:43.705+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20240430T170840, start_date=20240430T170843, end_date=20240430T170843
[2024-04-30T17:08:43.751+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-04-30T17:08:43.782+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
