[2024-04-30T16:56:14.335+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-04-30T16:56:09.848256+00:00 [queued]>
[2024-04-30T16:56:14.345+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-04-30T16:56:09.848256+00:00 [queued]>
[2024-04-30T16:56:14.346+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-04-30T16:56:14.346+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-04-30T16:56:14.347+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-04-30T16:56:14.360+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-04-30 16:56:09.848256+00:00
[2024-04-30T16:56:14.397+0000] {standard_task_runner.py:55} INFO - Started process 756 to run task
[2024-04-30T16:56:14.405+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2024-04-30T16:56:09.848256+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpijaal1r4']
[2024-04-30T16:56:14.409+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask is_api_available
[2024-04-30T16:56:14.491+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2024-04-30T16:56:09.848256+00:00 [running]> on host ec0cac6d8211
[2024-04-30T16:56:14.554+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-04-30T16:56:09.848256+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-30T16:56:09.848256+00:00
[2024-04-30T16:56:14.556+0000] {http.py:120} INFO - Poking: api/
[2024-04-30T16:56:14.565+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-04-30T16:56:14.568+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-04-30T16:56:14.846+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2024-04-30T16:56:14.863+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20240430T165609, start_date=20240430T165614, end_date=20240430T165614
[2024-04-30T16:56:14.912+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-04-30T16:56:14.941+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
